name: nvda_controller_client
description: Safe FFI bindings to nvdaControllerClient64.dll which is Windows-only and lets you push speech through the Nonvisual Desktop access screen reader
version: 0.2.1
repository: https://github.com/keithcat1/nvda-controller-dart


environment:
  sdk: '>=2.16.1 <4.0.0'




# dependencies:
#   path: ^1.8.0

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^2.1.1


dependencies: 
  ffi: ^2.0.2
  win32: ^5.0.3


ffigen:
  name: "NvdaControllerApi"
  description: "Safe bindings to the Windows NVDA screen reader controller, allowing text to be spoken and a few other operations"
  llvm-path:
    - 'C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\Llvm\x64'
    - 'C:\llvm-mingw'
    - 'C:\llvm'
    - 'C:\mingw64'
  output: 'lib/nvda_controller_client_bindings.dart'
  headers:
    entry-points:
      - 'nvdaController.h'
    include-directives:
      - '**nvdaController.h'
  functions:
    leaf:
      include:
        - '.*'

